
development:
  adapter: postgresql
  encoding: unicode
  database: cars_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: cars_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: cars_production
  pool: 5
  username:
  password:
